profile:
  default: "alexa"

server:
  host: "127.0.0.1"
  port: 4356

audio:
  adapter: "avfaudio"
  avfaudio:
    voice_processing: true

stt:
  adapter: "parakeet" # options: parakeet, whisper
  parakeet:
    model_id: "mlx-community/parakeet-tdt-0.6b-v3" # huggingface model id
    language: "en"
  whisper:
    model_id: "mlx-community/whisper-large-v3-turbo" # huggingface model id
    language: "en"

tts:
  adapter: "voxcpm2" # options: supertonic, voxcpm2
  supertonic:
    model_id: "Supertone/supertonic-3" # huggingface model id
    language: "en"
    intra_threads: # optional
    inter_threads: # optional
  voxcpm2:
    model_id: "openbmb/VoxCPM2" # huggingface model id
    load_denoiser: false

turn:
  adapter: "smart_turn"
  smart_turn:
    model_id: "mlx-community/smart-turn-v3" # huggingface model id
    threshold: 0.5
    max_audio_seconds: 30.0
    pre_roll_seconds: 0.5
    post_roll_seconds: 0.2
    min_speech_seconds: 0.3
    silence_seconds: 0.5
    fallback_silence_seconds: 1.8
    conversation_timeout_seconds: 30.0

vad:
  adapter: "silero_vad"
  silero_vad:
    engine: "mlx" # options: mlx, onnx
    model_id: "mlx-community/silero-vad" # huggingface model id
    model_path: "path://models/silero_vad.onnx" # required for onnx engine
    threshold: 0.5

wakeword:
  adapter: "openwakeword"
  openwakeword:
    threshold: 0.75
    patience: 2
    embedding_path: "path://models/embedding_model.onnx"
    melspec_path: "path://models/melspectrogram.onnx"
    frame_size: 1280