from typing import Any, Self

class NSObject:
    @classmethod
    def alloc(cls) -> Self: ...
    def init(self) -> Self | None: ...
    def __getattr__(self, name: str) -> Any: ...

class NSPoint:
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

class NSSize:
    width: float
    height: float
    def __init__(self, width: float = 0.0, height: float = 0.0) -> None: ...

class NSRect:
    origin: NSPoint
    size: NSSize
    def __init__(self, origin: NSPoint = ..., size: NSSize = ...) -> None: ...

class NSRange:
    location: int
    length: int
    def __init__(self, location: int = 0, length: int = 0) -> None: ...

def NSMakePoint(x: float, y: float) -> NSPoint: ...
def NSMakeSize(w: float, h: float) -> NSSize: ...
def NSMakeRect(x: float, y: float, w: float, h: float) -> NSRect: ...
def NSMakeRange(loc: int, length: int) -> NSRange: ...

class NSURL(NSObject):
    def path(self) -> str: ...

# Activation Policy
NSApplicationActivationPolicyRegular: int
NSApplicationActivationPolicyAccessory: int
NSApplicationActivationPolicyProhibited: int

# Modal Response
NSModalResponseOK: int
NSModalResponseCancel: int

# Window Style Mask
NSWindowStyleMaskTitled: int
NSWindowStyleMaskClosable: int
NSWindowStyleMaskMiniaturizable: int
NSWindowStyleMaskResizable: int

# Backing Store
NSBackingStoreBuffered: int

# View Autoresizing Mask
NSViewMinXMargin: int
NSViewWidthSizable: int
NSViewMaxXMargin: int
NSViewMinYMargin: int
NSViewHeightSizable: int
NSViewMaxYMargin: int

# Button / Bezel Style
NSBezelStyleRounded: int
NSBezelBorder: int

# Event Modifiers
NSEventModifierFlagCommand: int

# Pasteboard Types
NSPasteboardTypeString: str

class NSView(NSObject):
    def initWithFrame_(self, frame: NSRect) -> Self: ...
    def addSubview_(self, view: NSView) -> None: ...
    def setAutoresizingMask_(self, mask: int) -> None: ...
    def autoresizingMask(self) -> int: ...

class NSFont(NSObject):
    @classmethod
    def systemFontOfSize_(cls, size: float) -> NSFont: ...

class NSColor(NSObject):
    @classmethod
    def secondaryLabelColor(cls) -> NSColor: ...

class NSTextField(NSView):
    def setEditable_(self, flag: bool) -> None: ...
    def setBordered_(self, flag: bool) -> None: ...
    def setDrawsBackground_(self, flag: bool) -> None: ...
    def setTextColor_(self, color: NSColor) -> None: ...
    def setFont_(self, font: NSFont) -> None: ...
    def setStringValue_(self, value: str) -> None: ...
    def stringValue(self) -> str: ...

class NSButton(NSView):
    def setTitle_(self, title: str) -> None: ...
    def setBezelStyle_(self, style: int) -> None: ...
    def setTarget_(self, target: Any) -> None: ...
    def setAction_(self, action: str) -> None: ...
    def setKeyEquivalent_(self, key: str) -> None: ...
    def setKeyEquivalentModifierMask_(self, mask: int) -> None: ...

class NSTextContainer(NSObject):
    def setContainerSize_(self, size: NSSize) -> None: ...
    def setWidthTracksTextView_(self, flag: bool) -> None: ...

class NSEvent(NSObject):
    def characters(self) -> str | None: ...
    def modifierFlags(self) -> int: ...

class NSWindow(NSObject):
    def initWithContentRect_styleMask_backing_defer_(
        self,
        contentRect: NSRect,
        style: int,
        backingStoreType: int,
        flag: bool,
    ) -> Self: ...
    def setTitle_(self, title: str) -> None: ...
    def title(self) -> str: ...
    def setMinSize_(self, size: NSSize) -> None: ...
    def setReleasedWhenClosed_(self, flag: bool) -> None: ...
    def setFloatingPanel_(self, flag: bool) -> None: ...
    def setBecomesKeyOnlyIfNeeded_(self, flag: bool) -> None: ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def center(self) -> None: ...
    def contentView(self) -> NSView: ...
    def performClose_(self, sender: Any) -> None: ...
    def makeKeyAndOrderFront_(self, sender: Any) -> None: ...
    def orderFrontRegardless(self) -> None: ...
    def orderOut_(self, sender: Any) -> None: ...
    def makeFirstResponder_(self, responder: Any) -> bool: ...
    def canBecomeKeyWindow(self) -> bool: ...
    def canBecomeMainWindow(self) -> bool: ...

class NSTextView(NSView):
    def selectedRange(self) -> NSRange: ...
    def setSelectedRange_(self, range: NSRange) -> None: ...
    def string(self) -> str: ...
    def setString_(self, string: str) -> None: ...
    def rangeForUserCompletion(self) -> NSRange: ...
    def window(self) -> NSWindow | None: ...
    def setMinSize_(self, size: NSSize) -> None: ...
    def setMaxSize_(self, size: NSSize) -> None: ...
    def setVerticallyResizable_(self, flag: bool) -> None: ...
    def setHorizontallyResizable_(self, flag: bool) -> None: ...
    def setAutomaticQuoteSubstitutionEnabled_(self, flag: bool) -> None: ...
    def setAutomaticDashSubstitutionEnabled_(self, flag: bool) -> None: ...
    def setAutomaticTextReplacementEnabled_(self, flag: bool) -> None: ...
    def setAutomaticSpellingCorrectionEnabled_(self, flag: bool) -> None: ...
    def setFont_(self, font: NSFont) -> None: ...
    def setTextContainerInset_(self, size: NSSize) -> None: ...
    def setAllowsUndo_(self, flag: bool) -> None: ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def setEditable_(self, flag: bool) -> None: ...
    def setSelectable_(self, flag: bool) -> None: ...
    def isEditable(self) -> bool: ...
    def isSelectable(self) -> bool: ...
    def textContainer(self) -> NSTextContainer: ...
    def complete_(self, sender: Any) -> None: ...
    def scrollRangeToVisible_(self, range: NSRange) -> None: ...
    def keyDown_(self, event: NSEvent) -> None: ...

class NSScrollView(NSView):
    def setHasVerticalScroller_(self, flag: bool) -> None: ...
    def setBorderType_(self, borderType: int) -> None: ...
    def contentSize(self) -> NSSize: ...
    def setDocumentView_(self, view: NSView) -> None: ...

class NSPanel(NSWindow): ...

class NSSavePanel(NSPanel):
    @classmethod
    def savePanel(cls) -> NSSavePanel: ...
    def setNameFieldStringValue_(self, value: str) -> None: ...
    def setCanCreateDirectories_(self, flag: bool) -> None: ...
    def setAllowedFileTypes_(self, types: list[str]) -> None: ...
    def runModal(self) -> int: ...
    def URL(self) -> NSURL | None: ...

class NSPasteboard(NSObject):
    @classmethod
    def generalPasteboard(cls) -> NSPasteboard: ...
    def clearContents(self) -> int: ...
    def setString_forType_(self, string: str, dataType: str) -> bool: ...
    def stringForType_(self, dataType: str) -> str | None: ...

class NSApplication(NSObject):
    @classmethod
    def sharedApplication(cls) -> NSApplication: ...
    def setActivationPolicy_(self, policy: int) -> bool: ...
    def activationPolicy(self) -> int: ...
    def activateIgnoringOtherApps_(self, flag: bool) -> None: ...

def __getattr__(name: str) -> Any: ...
